import type { Hero } from "./types";

export const HEROES: Hero[] = [
  {
    name: "Sora",
    role: "Fighter",
    description: "Pejuang tangguh dengan dash cepat dan HP tinggi",
    skills: ["Dash Strike", "Shield Bash", "Berserker Mode"],
    hp: 5,
    damage: 3,
    speed: 4,
    color: "cyan",
    emoji: "S",
    image: "/assets/heroes/sora.png",
  },
  {
    name: "Zhuxin",
    role: "Mage",
    description: "Mage dengan projectile kuat dan ultimate perlambat area",
    skills: ["Arcane Bolt", "Frost Nova", "Blizzard"],
    hp: 2,
    damage: 5,
    speed: 3,
    color: "purple",
    emoji: "Z",
    image: "/assets/heroes/zhuxin.png",
  },
  {
    name: "Cici",
    role: "Fighter",
    description: "Yoyo mechanic unik, bisa bergerak sambil menyerang",
    skills: ["Yoyo Swing", "Spin Attack", "Yoyo Bind"],
    hp: 3,
    damage: 4,
    speed: 5,
    color: "pink",
    emoji: "C",
    image: "/assets/heroes/cici.png",
  },
  {
    name: "Nolan",
    role: "Assassin",
    description: "Multiple blinks, damage tertinggi, HP rendah",
    skills: ["Shadow Blink", "Phase Strike", "Death Mark"],
    hp: 1,
    damage: 5,
    speed: 5,
    color: "orange",
    emoji: "N",
    image: "/assets/heroes/nolan.png",
  },
];
